name: okmeta
version: '${project.version}'
main: com.maanraj514.Okmeta
api-version: '1.20'
authors: [maanraj514]
description: this is the core plugin that will be used by most if not all of maanraj514's plugins!
